feat: add binding for sorting
cmus-enjoyers/zmup pull request #11
Opened 2024-10-11 18:44 UTC by ThunderFlight

2024-10-13 21:06 UTC, SlikeDollar approved these changes

2024-10-14 05:54 UTC, VKTRenokh requested changes

2024-10-14 05:54 UTC, VKTRenokh commented on src/main.zig
> +
What will happen if i press j again after i pressed sj?

2024-10-17 13:48 UTC, VKTRenokh requested changes

2024-10-17 13:48 UTC, VKTRenokh commented on src/keybinds/timeout.zig
> +pub fn timeout_s(time_ms: u64, last_keybind: *[]const u8) void {
Rename this function please

2024-10-17 13:48 UTC, VKTRenokh commented on src/main.zig
>      defer {
return this line

2024-10-17 13:48 UTC, VKTRenokh commented on src/misc/timeout.zig
> +}
Are you sure we need this file?

2024-10-21 09:43 UTC, VKTRenokh approved these changes

2024-10-22 09:51 UTC, SlikeDollar approved these changes

2024-10-22 10:04 UTC, merged